Limit string paths to properties of the generic type on filters/sorts
dojo/stores pull request #104
Opened 2017-01-24 17:32 UTC by maier49

**Type:** feature

**Description:** 

Leverages `keyOf` to verify that the properties specified in filters and sorts are properties of the generic type of the filter/sort. This doesn't affect queries that use `JSONPointers`.   

Please review this checklist before submitting your PR:

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] The code passes the CI tests
* [ ] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

2017-01-24 18:27 UTC, dylans requested changes
Minor naming convention question, otherwise looks fine to me.

2017-01-24 18:27 UTC, dylans commented on tests/unit/query/createFilter.ts
> +			const pickFirstItem: FilterArray<NestedObj> = [
Are we ok with NestedObj and SimpleObj as names, or should we spell out the word Object in both?

2017-01-24 22:58 UTC, maier49 commented on tests/unit/query/createFilter.ts
> +			const pickFirstItem: FilterArray<NestedObj> = [
They should spell out Object, as the style guide makes it clear that we shouldn't be unnecessarily shortening variable names. I've updated them both.

2017-01-25 00:32 UTC, dylans approved these changes

2017-01-26 00:03 UTC, merged