Update readme
dojo/stores pull request #125
Opened 2017-04-07 00:16 UTC by maier49

**Type:** docs

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**
Updates the README now that compose is no longer being used.
Resolves #116

2017-04-07 12:42 UTC, dylans requested changes
Overall looks great, a few minor nitpicks to address.

2017-04-07 12:42 UTC, dylans commented on README.md
> +The result of querying or transforming will be implement the `QueryResult` interface.
typo... "will be implement the..."

2017-04-07 12:42 UTC, dylans commented on README.md
> +Unless the transform method is called without an idTransform, the result of any queries to a QueryableStore will be a `MappedQueryResult`, which includes additional data in its `StoreDelta` updates,
Should idTransform and QueryableStore be in code quotes?

2017-04-07 12:42 UTC, dylans commented on README.md
> +As with the observable store mixin, the locally tracked data in a `MappedQueryResult` has the potential to become out of sync with the underlying storage. If the source `ObservableStore` has `fetchAr
Is Observable store still a mixin, I thought it was now an interface, so perhaps change As with the observable store mixin to As with the `ObservableStoreInterface`

2017-04-07 14:57 UTC, maier49 commented on README.md
> +As with the observable store mixin, the locally tracked data in a `MappedQueryResult` has the potential to become out of sync with the underlying storage. If the source `ObservableStore` has `fetchAr
Changed it to `ObservableStore`

2017-04-08 13:30 UTC, dylans approved these changes

2017-04-11 14:44 UTC, merged