New tree store update
dojo/stores pull request #132
Opened 2017-05-19 07:44 UTC by maier49

**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Resolves: #106 

Adds a TreeStore and associated modules for observing and querying the store. This also includes some other small changes, like removing the `dataLength` property from fetch results, and adding a couple filter options. Those could be broken out into separate PRs that can be merged before this, but they're both necessary for this to be merged.

2017-05-19 18:05 UTC, dylans requested changes
This is a very large PR and this review is getting huge, so I'm going to stop here and let you address by documentation feedback! One thing I did not note is that terms within description should probably be using back-ticks more consistently, so please review that as well. Once you're done with these I'll take a look at the remaining parts of the PR. Note that my review has really been focused on the documentation rather than the code.

2017-05-19 18:05 UTC, dylans commented on README.md
> +	 * Collapses a the item(s) with the passed ID(s)
Collapses the item

2017-05-19 18:05 UTC, dylans commented on README.md
> +	 * @param id The id(s) to collapse
Should probably be The ID(s)... to be consistent with other parts of this README

2017-05-19 18:05 UTC, dylans commented on README.md
> +	 * @param itemOrId The ID of the element, or th element, to check the expanded status of
th -> the

2017-05-19 18:05 UTC, dylans commented on README.md
> +	 * Returns all children of the item with the specified ID, or an empty array of it has none.
of it has -> if it has

2017-05-19 18:05 UTC, dylans commented on README.md
> + but the tree store's options interface provides several flags that can be used to customize its behavior.
tree store -> TreeStore

2017-05-19 18:05 UTC, dylans commented on README.md
> +Any items returned through he TreeStore's API have a few additional values.
he -> the

2017-05-19 18:05 UTC, dylans commented on README.md
> +#### Store Context
Add a new line before this

2017-05-19 18:05 UTC, dylans commented on README.md
> +In order to use the observation and query APIs with a `TreeStore`, the `ObservableTreeStore` and `QueryableTreeStore` classes, provided in the `tree` package, should be used. These APIs can be used m
"In order to use the observation and query APIs with a `TreeStore`, the `ObservableTreeStore` and `QueryableTreeStore` classes, provided in the `tree` package, should be used." -> "In order to use the observation and query APIs with a `TreeStore`, use the `ObservableTreeStore` and `QueryableTreeStore` classes which are provided in the `tree` package."

2017-05-19 18:05 UTC, dylans commented on README.md
> +In order to use the observation and query APIs with a `TreeStore`, the `ObservableTreeStore` and `QueryableTreeStore` classes, provided in the `tree` package, should be used. These APIs can be used m
"same manner as for a normal store" -> "same manner as a normal store"

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * The state of the store after all of these updates.  Doesn't necessarily
let's be more specific than "these updates"

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * The state of the store after all of these updates.  Doesn't necessarily
Doesn't necessarily -> be more specific, e.g. The state does not necessarily reflect...

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * storage based on the known updates if fetchAroundUpdates is false
fetchAroundUpdates -> `fetchAroundUpdates`

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * The state of the store before any of these updates.
same comment as earlier

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * Contains info were previously and still are in the tracked collection but have changed position, regardless of
"Contains info were previously" not sure what you mean here

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * Contains info for any items that were formerly in the tracked collection and are now not, regardless of how
are now not is a bit tough to read...  maybe "Contains information for any items that were formerly in the tracked collection and were removed"

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * Contains info for any items that are now in the tracked collection and formerly were not, regardless of how
info -> information

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * Creates a query transform result with a range built based on the provided start and count
"built based on" reads oddly

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * whether their position has shifted or differentiating between updates and adds
This last sentence is a bit confusing, any way to make it more clear/explicit?

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * whether their position has shifted or differentiating between updates and adds
Same comment as earlier

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * These overrides aren't actually changing the signature, they are just necessary to make typescript happy about
aren't -> are not

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * These overrides aren't actually changing the signature, they are just necessary to make typescript happy about
TypeScript

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * These overrides aren't actually changing the signature, they are just necessary to make typescript happy about
typescript - > TypeScript

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * items are deleted an `ItemUpdate` with the item's ID and no item property will be sent out. When all of the
sent out -> sent or returned?

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * An optional store to use. If a store is provided this way and data is provided, the initial add will not block
this way -> be more specific

2017-05-19 18:05 UTC, dylans commented on src/interfaces.d.ts
> +	 * @param itemOrId The ID of the element, or th element, to check the expanded status of
th -> the

2017-05-19 22:14 UTC, maier49 commented
@dylans I think I've addressed the documentation related feedback you've provided so far.

2017-05-22 12:08 UTC, dylans requested changes
Lots of documentation nits

2017-05-22 12:08 UTC, dylans commented on src/interfaces.d.ts
> +	 * Returns tree data, which is an object containing the expanded flag, the hasChildren flag, and the treeStoreLevel
Should hasChildren and treeStoreLength be inside backticks?

2017-05-22 12:08 UTC, dylans commented on src/interfaces.d.ts
> +	 * sorted. If the root has no children, it will always be at the end. This will be overridden by _shouldSortRootsByData
at the end of what?

2017-05-22 12:08 UTC, dylans commented on src/interfaces.d.ts
> +	 * sorted. If the root has no children, it will always be at the end. This will be overridden by _shouldSortRootsByData
_shouldSortRootsByData -> `_shouldSortRootsByData` ?

2017-05-22 12:08 UTC, dylans commented on src/interfaces.d.ts
> +	 * If true, root nodes will be sorted by their own data. This will override shouldSortRootsByChildren if both are true
shouldSortRootsByChildren -> `shouldSortRootsByChildren` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> + * Sorts the provided root nodes based on the values of the array of firstChildren. This assumes that the
firstChildren -> `firstChildren` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Maps item IDs to a ChildData object, which contains an array of the child nodes belonging to the item with the
ChildData -> `ChildData1` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Index for root nodes, mapping their IDs to their positions with in the root collection
with in -> within

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * If true, root nodes will be sorted by their own data. This will override shouldSortRootsByChildren if both are true
shouldSortRootsByChildren -> `shouldSortRootsByChildren` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * If true, the root nodes will be sorted by comparing the first child of each, after their children have been
first child of each -> first child of each root node

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * sorted. If the root has no children, it will always be at the end. This will be overridden by shouldSortRootsByData
at the end of what?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * sorted. If the root has no children, it will always be at the end. This will be overridden by shouldSortRootsByData
shouldSortRootsByData -> `shouldSortRootsByData`

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param state State of the TreeStorage
TreeStorage -> `TreeStorage` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param toHide Set of items that are excluded by a range but included because their childre are within the same range
"that are excluded by a range but included" can we be more explicit here?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param toHide Set of items that are excluded by a range but included because their childre are within the same range
childre -> children

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Build a local copy of the child map that contains only the children of expanded nodes(all nodes if expanded
nodes(all -> nodes (all

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param expanded The optional lis of expanded elements
lis -> list

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * querying and building the tree, and which can optionally be shown by setting the shouldShowParentsExcludedByRange flag
shouldShowParentsExcludedByRange -> `shouldShowParentsExcludedByRange`

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * rejectOverwrite is true, in which case the operation will fail.
rejectOverwrite -> `rejectOverwrite` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param rejectOverwrite Whether to fail if existing items are contained in newItems
newItems -> `newItems` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param ids The ids of the items to delete
ids -> IDs

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param totalCount
Explanation missing for totalCount

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Re builds an index starting from the specified index in the array
Re builds -> Rebuilds

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Retrieves the first child of each root node, sorting their children if they haven't been sorted already, and
haven't -> have not

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * then delegates to sortRoots
sortRoots -> `sortRoots` ?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +			// Don't control the order operations are executed in, but make sure that the results
Don't -> Do not

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +		// Don't control the order operations are executed in, but make sure that the results
Don't -> Do not

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * @param parentOrId
summary missing for these two params

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +	 * Returns tree data, which is an object containing the expanded flag, the hasChildren flag, and the treeStoreLevel
backticks?

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +			// Don't control the order operations are executed in, but make sure that the results
Don't -> Do not

2017-05-22 12:08 UTC, dylans commented on src/storage/TreeStorage.ts
> +			// Don't control the order operations are executed in, but make sure that the results
Don't -> Do not

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
> + * @param ids - The IDS to build the _index for
IDS -> IDs

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
> + * the _index if for, or that the array of items the IDs represent is in the same order, which is already the case
_index -> `_index` ?

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
> +	 * @param update
missing summary

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
> +	 * Merges the latest queued updates, updates the local data and _index based on the latest data,
_index -> `_index` ?

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
>  	 * of observers. If after is provided, it is assumed that that is the latest data for the store, if it is not provided
after -> `after` ?

2017-05-22 12:08 UTC, dylans commented on src/store/ObservableStore.ts
> +	 * the local data and _index to the newly retrieved data.
`_index` ?

2017-05-22 12:08 UTC, dylans commented on src/store/QueryResult.ts
> +		// If nextQuery isn't defined, then there are no transformations, so we can add the
`nextQuery` ?

2017-05-22 12:08 UTC, dylans commented on src/store/QueryResult.ts
> +		// If nextQuery isn't defined, then there are no transformations, so we can add the
isn't -> is not

2017-05-22 12:08 UTC, dylans commented on src/store/QueryableStore.ts
> + * @param store
missing parameter summaries

2017-05-22 12:08 UTC, dylans commented on src/store/QueryableStore.ts
> + * @param store
Missing parameter summaries

2017-05-22 12:08 UTC, dylans commented on src/store/QueryableStore.ts
> + * @param store
Missing parameter summaries

2017-05-22 12:08 UTC, dylans commented on src/store/QueryableStore.ts
> + * @param store
Missing parameter summaries

2017-05-22 12:08 UTC, dylans commented on src/store/QueryableStore.ts
> + * @param store
Missing parameter summaries

2017-05-22 12:08 UTC, dylans commented on src/store/tree/ObservableTreeStore.ts
> +	 * @param update
Missing parameter summary

2017-05-22 12:08 UTC, dylans commented on src/utils.ts
> + * @param filterOrTest
Missing parameter summary

2017-05-22 12:08 UTC, dylans commented on src/utils.ts
> + * @param queryOrTransformation
Missing parameter summary

2017-05-22 12:08 UTC, dylans commented on src/utils.ts
> + * @param transform
Missing parameter summaries

2017-05-25 18:01 UTC, maier49 commented
The second round of documentation issues has been addressed now.

2017-06-18 19:19 UTC, dylans approved these changes
ok, I'll approve for the things I've checked for so I'm not still blocking this, though this should probably get a further API review from someone like Kit, Ant, or Matt perhaps?

2017-11-07 10:19 UTC, agubler commented
Closing since the latest version of stores has landed

2017-11-07 10:19 UTC, closed without merging