Indexed db
dojo/stores pull request #46
Opened 2016-11-14 16:33 UTC by maier49

**Type:** feature

**Description:** 

Adds a `Storage` implementation that interfaces with IndexedDB. Depends on 
#32 .

**Related Issue:** #45

Please review this checklist before submitting your PR:

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] The code passes the CI tests
* [x] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [ ] The code is ready to be merged

2017-01-04 05:49 UTC, maier49 commented
This now adds `totalLength` to fetch results so it should be merged after #94

2017-01-13 22:38 UTC, agubler requested changes
couple minor comments

2017-01-13 22:38 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +			// request.error.message = request.webkitErrorMessage;
remove commented out code

2017-01-13 22:38 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	const db = state.db!;
we don't use `!` to skip `strictNullChecks` in source code (only in tests)

2017-01-13 22:38 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	let firstFilterOrOp: SimpleFilter<any> | BooleanOp  | undefined = filterChain && filterChain[0];
could be `const`

2017-01-13 22:38 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +function getKeyRangeAndIndex(
if this was typed like this you could drop the `| undefined` part
```ts
getKeyRangeAndIndex(state: IndexedDBState<any>, objectStore: IDBObjectStore, filter?: SimpleFilter<any>, secondFilter?: SimpleFilter<any>)
```

2017-01-23 10:33 UTC, agubler commented on tests/unit/storage/createInMemoryStorage.ts
> +		// 'Should return `isUpdate=false` when item doesn\'t exist.'(this: any) {
Do we want to leave commented out code, even in tests? If there is a reason then probably should add a comment to that affect.

2017-01-23 10:36 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	else {
Don't need this in an `else` block

2017-01-23 11:16 UTC, agubler requested changes
A couple of minor comments.

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	else {
I don't think we need all this nesting. Maybe something like this?

```ts
function getKey(filter: SimpleFilter<any>): string | undefined {
    const path = filter.path;
    if (!path) {
        return undefined;
    }
    if (typeof path === 'string') {
        return path;
    }
    const segments = path.segments();
    if (segments.length === 1) {
        return segments[0];
    }
    return undefined;
}
```

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	if (typeof lowerBound !== 'undefined' && typeof upperBound !== 'undefined') {
Same here although doesn't help readability as much, but can all be `if`s with a `return undefined` after

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	let returnValue: {
Can just return from the function in place instead of assigning the return value and returning from the end, would remove the need for this `let`. Also I would defined this as an interface outside of the function.

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +			const fetchResult: FetchResult<{}> = <any> state.dbInitializationPromise.then(
It's very hard to review this function, is there any sensible way this can be broken up into specific functionality/concerns?

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +				})).then((updatedItems) => ({
I haven't noticed anywhere else in the PR (there may be other occurrences) but I believe the style guide mentions `.then`s need to be new lined.

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +		add(this: Storage<{}, {}>, items: {}[], options?: CrudOptions): Promise<UpdateResults<{}>> {
you can a default inline to the function args that might help here.

```ts
add(this: Storage<{}, {}>, items: {}[], options: CrudOptions = { rejectOverwrite = true }): Promise<UpdateResults<{}>> {
    return this.put(items, options).then((results) => {
        results.type = StoreOperation.Add;
        return results;
    });
}

2017-01-23 11:16 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +	initialize<T, O>(instance: Storage<T, O>, options?: IndexedDBOptions<T, CrudOptions>) {
can just do `, options: IndexedDBOptions<T, CrudOptions> = {}`

2017-01-24 05:19 UTC, maier49 commented on src/storage/createIndexedDBStorage.ts
> +			const fetchResult: FetchResult<{}> = <any> state.dbInitializationPromise.then(
I've broken this up, as well as a few other sections, into more atomic functions.

2017-01-24 05:20 UTC, maier49 commented on src/storage/createIndexedDBStorage.ts
> +				})).then((updatedItems) => ({
Fixed. I know this style is more consistent with having `else` on a new line, and understand the reasoning for it, but I just wanted to note that I find it very awkward to read.

2017-01-24 05:20 UTC, maier49 commented
@agubler Your latest round of comments should be resolved.

2017-01-26 10:47 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +					.then((updatedItems) => ({
is this indentation off?

2017-01-26 10:47 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +		add(
weird formatting

2017-01-26 10:47 UTC, agubler commented on src/storage/createIndexedDBStorage.ts
> +					.then((updatedItems) => ({
indentation again?

2017-01-27 07:03 UTC, maier49 commented
@agubler I somehow managed to misread the style guide when I updated the indentation of the 
`.then`s. Hopefully those formatting issues are resolved now.

2017-01-31 14:45 UTC, agubler approved these changes
:+1:

2017-01-31 16:14 UTC, merged