Update get and identify APIs to return the item/id in one item case.
dojo/stores pull request #61
Opened 2016-12-01 21:33 UTC by lzhoucs

**Type:** feature

**Description:** 
Update get and identify APIs to return the item/id instead of the one item.id array in one item case.

**Related Issue:** #60 

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] The code passes the CI tests
* [x] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

2016-12-02 16:11 UTC, maier49 requested changes

2016-12-02 16:11 UTC, maier49 commented on src/store/createStore.ts
> +	get(this: Store<{}, {}, any>, ids: string[] | string): Promise<any> {
Could we type the return here to `Promise<{} | {}[]>`? That way it provides at least some guarantee about the return type in the implementation.

2016-12-02 16:11 UTC, maier49 commented on src/store/createStore.ts
> +	identify(this: Store<{}, {}, any>, items: {}[] | {}): any {
Same question here really, could this return `string | string[]`?

2016-12-02 17:55 UTC, lzhoucs commented on src/store/createStore.ts
> +	get(this: Store<{}, {}, any>, ids: string[] | string): Promise<any> {
Good point. I have made the change.

2016-12-02 17:57 UTC, lzhoucs commented on src/store/createStore.ts
> +	identify(this: Store<{}, {}, any>, items: {}[] | {}): any {
Although `get` can be done this way, `identify` can't as I tried. Please let me know if you have ways to get around this and I am happy to make it type safer.

2016-12-02 18:01 UTC, lzhoucs commented
Just a note, the CI has been hanging on `iphone 9.3` which is not caused by changes in this PR:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
I've seem this happen before. It seems it only fails occasionally.

2016-12-09 17:00 UTC, maier49 approved these changes

2016-12-09 17:00 UTC, merged